services:
  frontend:
    container_name: "react-frontend"
    build:
      context: ./frontend
    ports:
      - "80:5173"

  backend:
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
    container_name: "fastapi-backend"
    build:
      context: ./backend
    ports:
      - "8000:8000"